version: 2.1

  jobs:
     build:
         docker:
             - image: cimg/python:3.11
        steps:
          - checkout
          - run: README.md 

workflow:
    build_now:
        jobs:
          -build